### PR TITLE
Codespell the whole source to fix typos + delete[] change

### PR DESCRIPTION
**Pull request by akien-mga**
It would have been simpler for me to just run codespell myself and commit the changes, but I wanted to preserve @coringao's credits, so here it is.

### CODE REVIEW

**Comment by akien-mga** [comment]
Part of #12.

**Comment by akien-mga** [comment]
Once this one is merged, I'll start cleaning all .cpp and .h files to remove trailing spaces, homegenize indentation, etc., so that we have a clean base to work on together.

**Comment by akien-mga** [comment]
@strycore It would have been better to merge this one with a merge commit and keep all three commits separate IMO. But well, it's too late :)

**Comment by strycore** [comment]
Ah, I saw your comment after merging the other PR ^^

**Comment by akien-mga** [comment]
Erf, I had also commented about this in the other PR...

**Pull request merged**
