### PR TITLE
Config switch for minizip + add .gitattributes for LF line endings + more misc changes

### PR DESCRIPTION
**Pull request by akien-mga**

### CODE REVIEW

**Comment by akien-mga** [comment]
Oops, I actually forgot to change the include "unzip/unzip.h" for d99cda2, I'll fix that.

**Comment by akien-mga** [comment]
Now fixed.

**Comment by akien-mga** [comment]
I've added a couple more minor changes. Now I want to have a look at a Qt5 port, but I'll do that in a separate branch to avoid cluttering this PR.

**Comment by akien-mga** [comment]
Actually the Qt5 support was easy as pie: one only needs to run Qt5's qmake and it works out of the box. So I've just updated the README to mention Qt5 support.

**Comment by akien-mga** [comment]
Oops, looks like there are merge conflicts. I'll redo my changes in a few smaller PRs.

**Comment by strycore** [comment]
Ok, tell me when this PR is ready and I'll merge it.

**Comment by akien-mga** [comment]
Superseded by #7 and #8.

**Pull request closed without merging**
